'use client';

import React from 'react';
import Link from 'next/link';
import { Sparkles, ArrowRight, Quote, CheckCircle2, TrendingUp, Users } from 'lucide-react';

export default function CaseStudiesShowcase() {
  const caseStudies = [
    {
      company: 'BlogSEO',
      logo: '/lp/logo-blogseo-white.png',
      tagline: 'Autonomous AI programmatic SEO engine',
      metric: '+340%',
      metricLabel: 'Inbound Trial Velocity',
      quote: 'Naano completely replaced our uncertain Google Ads spend. One post from a verified tech creator drove 85 qualified signups in the first 24 hours.',
      author: 'Vincent',
      role: 'Founder & CEO, BlogSEO',
      href: '/case-studies/blogseo',
      creatorsCount: '3 Creators',
      pipeline: '€24,500 Pipeline',
    },
    {
      company: 'lemlist',
      logo: '/lp/logo-lemlist-white.png',
      tagline: 'Leading cold outreach & sales automation',
      metric: '42 Demos',
      metricLabel: 'Booked in 7 Days',
      quote: 'B2B buyers ignore cold pitch emails, but they read breakdowns from trusted practitioners. Naano gave us direct access to our exact ICP.',
      author: 'Guillaume Moubeche',
      role: 'CEO, lemlist',
      href: '/case-studies/blogseo',
      creatorsCount: '5 Creators',
      pipeline: '€38,000 Pipeline',
    },
    {
      company: 'Leadbay.ai',
      logo: '/lp/logo-leadbay-white.png',
      tagline: 'AI account research & MCP infrastructure',
      metric: '384 Clicks',
      metricLabel: 'With 18% Trial Conv.',
      quote: 'Launching our new Claude MCP feature required technical credibility. The video demo post by Robin Delaere went viral across LinkedIn engineering circles.',
      author: 'Thomas Marcelle',
      role: 'Head of Growth, Leadbay',
      href: '/case-studies/blogseo',
      creatorsCount: '2 Creators',
      pipeline: '€16,200 Pipeline',
    },
  ];

  return (
    <section className="py-24 sm:py-28 bg-[#070D0A] text-white border-y border-emerald-950/60 relative overflow-hidden">
      {/* Atmospheric ambient glows matching luxury fintech aesthetic */}
      <div className="absolute top-0 right-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-1/4 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-16">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-950/80 text-emerald-400 text-xs font-bold border border-emerald-500/30 uppercase tracking-wider mb-3 shadow-xs">
              <TrendingUp className="w-3.5 h-3.5 text-emerald-400" />
              <span>Verified Results &amp; ROI</span>
            </div>
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white tracking-tight">
              Real Revenue Generated by Real Creators
            </h2>
            <p className="mt-3 text-slate-400 text-sm sm:text-base max-w-xl leading-relaxed">
              See how modern B2B SaaS companies scale outbound pipeline and customer acquisition with Naano creator partnerships.
            </p>
          </div>

          <Link
            href="/case-studies/blogseo"
            className="inline-flex items-center gap-2 text-xs sm:text-sm font-bold text-emerald-400 hover:text-emerald-300 hover:underline transition-colors shrink-0"
          >
            <span>Read full BlogSEO breakdown</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        {/* Case Study Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {caseStudies.map((cs, idx) => (
            <div
              key={idx}
              className="rounded-3xl bg-[#0D1812]/90 border border-emerald-500/20 p-8 flex flex-col justify-between shadow-2xl hover:border-emerald-400/50 hover:bg-[#112018] transition-all duration-300 group relative"
            >
              <div>
                {/* Logo & Category */}
                <div className="flex items-center justify-between mb-6 pb-6 border-b border-emerald-950/80">
                  <img
                    src={cs.logo}
                    alt={cs.company}
                    className="h-7 max-w-[130px] object-contain opacity-85 group-hover:opacity-100 transition-opacity"
                  />
                  <span className="text-[11px] font-bold text-emerald-400/90 font-mono bg-emerald-950/60 border border-emerald-500/20 px-2.5 py-0.5 rounded-full">
                    {cs.creatorsCount}
                  </span>
                </div>

                {/* Key Metric Hero */}
                <div className="mb-6">
                  <div className="text-4xl sm:text-5xl font-black font-mono tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-teal-300">
                    {cs.metric}
                  </div>
                  <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mt-1.5">
                    {cs.metricLabel}
                  </div>
                </div>

                {/* Quote */}
                <div className="relative mb-6">
                  <Quote className="w-6 h-6 text-emerald-500/40 mb-2 rotate-180" />
                  <p className="text-sm text-slate-300 leading-relaxed italic">
                    &quot;{cs.quote}&quot;
                  </p>
                </div>
              </div>

              {/* Author Footer */}
              <div className="pt-6 border-t border-emerald-950/80 flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-white">{cs.author}</div>
                  <div className="text-[11px] text-slate-400 mt-0.5">{cs.role}</div>
                </div>

                <div className="text-right">
                  <div className="text-xs font-bold text-emerald-400 font-mono">
                    {cs.pipeline}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
