'use client';

import React from 'react';
import Link from 'next/link';
import { Sparkles, ArrowRight, Quote, CheckCircle2, TrendingUp, Users } from 'lucide-react';

export default function CaseStudiesShowcase() {
  const caseStudies = [
    {
      company: 'BlogSEO',
      logo: '/lp/logo-blogseo.png',
      tagline: 'Autonomous AI programmatic SEO engine',
      metric: '+340%',
      metricLabel: 'Inbound Trial Velocity',
      quote: 'Naano completely replaced our uncertain Google Ads spend. One post from a verified tech creator drove 85 qualified signups in the first 24 hours.',
      author: 'Vincent',
      role: 'Founder & CEO, BlogSEO',
      href: '/case-studies/blogseo',
      creatorsCount: '3 Creators',
      pipeline: '€24,500 Pipeline',
    },
    {
      company: 'lemlist',
      logo: '/lp/logo-lemlist.png',
      tagline: 'Leading cold outreach & sales automation',
      metric: '42 Demos',
      metricLabel: 'Booked in 7 Days',
      quote: 'B2B buyers ignore cold pitch emails, but they read breakdowns from trusted practitioners. Naano gave us direct access to our exact ICP.',
      author: 'Guillaume Moubeche',
      role: 'CEO, lemlist',
      href: '/case-studies/blogseo',
      creatorsCount: '5 Creators',
      pipeline: '€38,000 Pipeline',
    },
    {
      company: 'Leadbay.ai',
      logo: '/lp/logo-leadbay.png',
      tagline: 'AI account research & MCP infrastructure',
      metric: '384 Clicks',
      metricLabel: 'With 18% Trial Conv.',
      quote: 'Launching our new Claude MCP feature required technical credibility. The video demo post by Robin Delaere went viral across LinkedIn engineering circles.',
      author: 'Thomas Marcelle',
      role: 'Head of Growth, Leadbay',
      href: '/case-studies/blogseo',
      creatorsCount: '2 Creators',
      pipeline: '€16,200 Pipeline',
    },
  ];

  return (
    <section className="py-24 bg-white border-b border-slate-200/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-16">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 text-emerald-700 text-xs font-bold border border-emerald-100 uppercase tracking-wider mb-3">
              <TrendingUp className="w-3.5 h-3.5" />
              <span>Verified Results</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Real Revenue Generated by Real Creators
            </h2>
            <p className="mt-2 text-slate-600 text-sm sm:text-base max-w-xl">
              See how modern B2B SaaS companies scale outbound pipeline and customer acquisition with Naano creator partnerships.
            </p>
          </div>

          <Link
            href="/case-studies/blogseo"
            className="inline-flex items-center gap-2 text-xs sm:text-sm font-bold text-indigo-600 hover:text-indigo-700 hover:underline"
          >
            <span>Read full BlogSEO breakdown</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        {/* Case Study Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {caseStudies.map((cs, idx) => (
            <div
              key={idx}
              className="rounded-3xl bg-slate-50/80 border border-slate-200/80 p-8 flex flex-col justify-between hover:shadow-xl hover:border-indigo-200 transition-all duration-300 group"
            >
              <div>
                {/* Logo & Category */}
                <div className="flex items-center justify-between mb-6 pb-6 border-b border-slate-200/60">
                  <img
                    src={cs.logo}
                    alt={cs.company}
                    className="h-7 max-w-[130px] object-contain grayscale group-hover:grayscale-0 transition-all"
                  />
                  <span className="text-[11px] font-bold text-slate-400 font-mono">
                    {cs.creatorsCount}
                  </span>
                </div>

                {/* Key Metric Hero */}
                <div className="mb-6">
                  <div className="text-4xl sm:text-5xl font-black text-slate-900 font-mono tracking-tight text-indigo-600">
                    {cs.metric}
                  </div>
                  <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mt-1">
                    {cs.metricLabel}
                  </div>
                </div>

                {/* Quote */}
                <div className="relative mb-6">
                  <Quote className="w-6 h-6 text-slate-300 mb-2 rotate-180" />
                  <p className="text-sm text-slate-700 leading-relaxed italic">
                    &quot;{cs.quote}&quot;
                  </p>
                </div>
              </div>

              {/* Author Footer */}
              <div className="pt-6 border-t border-slate-200/60 flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-slate-900">{cs.author}</div>
                  <div className="text-[11px] text-slate-500">{cs.role}</div>
                </div>

                <div className="text-right">
                  <div className="text-xs font-bold text-emerald-600 font-mono">
                    {cs.pipeline}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
