'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { MessageCircle } from 'lucide-react';

export default function HeroSection() {
  const brandLogos = [
    { type: 'casestudy', src: '/lp/logo-blogseo.png', alt: 'BlogSEO' },
    { type: 'logo', src: '/lp/logo-lemlist.png', alt: 'lemlist', maxH: '42px' },
    { type: 'logo', src: '/lp/logo-folk.png', alt: 'folk.', maxH: '30px' },
    { type: 'logo', src: '/lp/logo-leadbay.png', alt: 'Leadbay', maxH: '28px' },
    { type: 'logo', src: '/lp/logo-ringover.png', alt: 'Ringover', maxH: '42px' },
    { type: 'logo', src: '/lp/logo-attio.jpg', alt: 'Attio', maxH: '42px' },
    { type: 'logo', src: '/lp/logo-lagrowthmachine.png', alt: 'La Growth Machine', maxH: '34px' },
    { type: 'logo', src: '/lp/logo-gojiberry.png', alt: 'Gojiberry', maxH: '32px' },
    { type: 'logo', src: '/lp/logo-chatseo.png', alt: 'ChatSEO', maxH: '40px' },
    { type: 'logo', src: '/lp/logo-abyssale.png', alt: 'Abyssale', maxH: '30px' },
  ];

  return (
    <section className="relative min-h-[96vh] flex flex-col justify-between pt-28 sm:pt-36 pb-12 overflow-hidden bg-[#CFE8F9]">
      {/* 100% Genuine Naano Hero Clouds Backdrop */}
      <div 
        className="absolute inset-0 bg-cover bg-center pointer-events-none -z-10"
        style={{ 
          backgroundImage: "url('/lp/hero-clouds-cotton-blue-v7.png')",
          backgroundPosition: '50% 50%',
          backgroundSize: 'cover'
        }}
      />

      <div className="max-w-[1672px] mx-auto px-6 sm:px-14 text-center flex flex-col items-center my-auto w-full">
        {/* Eyebrow Pill Badge */}
        <div className="inline-flex items-center gap-2.5 bg-white border border-[#EBE9E5] shadow-[0_1px_2px_rgba(23,24,28,0.04)] rounded-full py-2 px-4 mb-8">
          {/* Twitter / X icon */}
          <svg width="15" height="15" viewBox="0 0 24 24" fill="#17181C">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
          </svg>
          {/* LinkedIn icon */}
          <svg width="18" height="18" viewBox="0 0 24 24" fill="#0A66C2">
            <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
          </svg>
          <span className="text-[14.5px] sm:text-[15px] font-medium text-[#33353B]">
            Where B2B brands work with creators
          </span>
        </div>

        {/* Headline */}
        <h1 className="text-[52px] sm:text-[68px] lg:text-[77px] font-semibold tracking-[-0.04em] text-[#17181C] leading-[1.05] max-w-[980px]">
          The B2B LinkedIn<br />
          Creator Marketplace<span className="text-[#111318]">.</span>
        </h1>

        {/* Subtitle */}
        <p className="mt-7 text-lg sm:text-[21px] text-[#43454C] max-w-[660px] font-normal leading-[1.5]">
          Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.
        </p>

        {/* CTA Buttons */}
        <div className="mt-11 flex flex-col sm:flex-row items-center justify-center gap-6">
          <Link
            href="/register"
            className="inline-flex items-center gap-2.5 bg-[#17181C] hover:bg-black text-white text-[16px] font-semibold px-7 py-4 rounded-[12px] shadow-sm transition-all"
          >
            <span>Launch a campaign</span>
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="4" y1="12" x2="20" y2="12" />
              <polyline points="13 5 20 12 13 19" />
            </svg>
          </Link>

          <Link
            href="#how-it-works"
            className="inline-flex items-center gap-2 text-[#17181C] hover:text-black text-[16.5px] font-semibold px-4 py-4 transition-colors"
          >
            <span>See how Naano works</span>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#111318" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="4" y1="12" x2="20" y2="12" />
              <polyline points="13 5 20 12 13 19" />
            </svg>
          </Link>
        </div>

        {/* Trust Header */}
        <div className="mt-9 flex items-center justify-center gap-2.5 text-[#55575E]">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 2 L20 5 V11 C20 16.5 16.5 20.5 12 22 C7.5 20.5 4 16.5 4 11 V5 Z" />
            <path d="M9 12 L11 14 L15 9.5" />
          </svg>
          <span className="text-[15.5px] font-medium">Trusted by modern B2B teams</span>
        </div>

        {/* Authentic Continuous Infinite Marquee with Original Assets */}
        <div className="mt-12 w-full overflow-hidden relative" style={{ maskImage: 'linear-gradient(90deg, transparent, #000 8%, #000 92%, transparent)', WebkitMaskImage: 'linear-gradient(90deg, transparent, #000 8%, #000 92%, transparent)' }}>
          <div className="flex items-center animate-marquee whitespace-nowrap">
            {brandLogos.concat(brandLogos).map((item, idx) => (
              <div key={idx} className="shrink-0 px-9 flex items-center justify-center">
                {item.type === 'casestudy' ? (
                  <div className="inline-flex items-center gap-3 border border-[#E4E1DC] rounded-full py-2 pl-4 pr-2.5 bg-white shadow-[0_2px_10px_rgba(23,24,28,0.05)]">
                    <img src={item.src} alt={item.alt} className="h-[19px] max-w-[120px] object-contain block" />
                    <span className="inline-flex items-center gap-1.5 bg-[rgba(17,19,24,0.06)] text-[#111318] text-[11px] font-bold tracking-wider py-1 px-2.5 rounded-full">
                      CASE STUDY
                      <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
                        <line x1="5" y1="12" x2="19" y2="12" />
                        <polyline points="12 5 19 12 12 19" />
                      </svg>
                    </span>
                  </div>
                ) : (
                  <div className="w-[152px] h-[48px] flex items-center justify-center">
                    <img
                      src={item.src}
                      alt={item.alt}
                      style={{ maxHeight: item.maxH, maxWidth: '152px' }}
                      className="object-contain block grayscale opacity-55 hover:grayscale-0 hover:opacity-100 transition-all duration-300"
                    />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Floating Bottom Action Buttons */}
      <div className="fixed bottom-5 right-6 z-40 flex items-center gap-3">
        <button
          onClick={() => alert('Naano uses cookies to analyze traffic and provide optimal marketplace experiences.')}
          className="bg-[#17181C] hover:bg-black text-white text-xs font-semibold px-3.5 py-1.5 rounded-full shadow-lg cursor-pointer"
        >
          Cookies
        </button>

        <button
          onClick={() => alert('Naano B2B Support: Available 24/7')}
          className="w-12 h-12 rounded-full bg-[#202124] hover:bg-black text-white shadow-xl flex items-center justify-center cursor-pointer transition-transform hover:scale-105"
          title="Customer Support"
        >
          <MessageCircle className="w-5 h-5 fill-white text-[#202124]" />
        </button>
      </div>
    </section>
  );
}
