'use client';

import React, { useState } from 'react';
import Link from 'next/link';

export interface LeaderboardCreator {
  id: string;
  rank: number;
  name: string;
  avatarUrl: string;
  cardUrl: string;
  subtitle?: string;
  impressions: number;
  posts: number;
}

interface LeaderboardSectionProps {
  creators: LeaderboardCreator[];
}

export default function LeaderboardSection({ creators }: LeaderboardSectionProps) {
  const [activeTab, setActiveTab] = useState<'impressions' | 'posts'>('impressions');

  // Sort and calculate max values based on active tab
  const sorted = [...creators].sort((a, b) => {
    if (activeTab === 'impressions') {
      return b.impressions - a.impressions;
    }
    return b.posts - a.posts;
  });

  const maxVal = Math.max(
    ...sorted.map((c) => (activeTab === 'impressions' ? c.impressions : c.posts)),
    1
  );

  return (
    <section className="bg-white rounded-3xl p-6 sm:p-8 border border-[#E2E8F0] shadow-sm mt-8">
      {/* Header with Title and Toggle Tabs */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-100">
        <div>
          <h2 className="text-xl font-bold text-[#111827] tracking-tight">
            Naano campaign leaderboard
          </h2>
          <p className="text-xs text-[#64748B] mt-1">
            Estimated impressions generated by sponsored posts published for Naano brand collaborations.
          </p>
        </div>

        {/* Toggle Switch Pill */}
        <div className="inline-flex items-center p-1 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] self-start sm:self-auto shrink-0">
          <button
            type="button"
            onClick={() => setActiveTab('impressions')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
              activeTab === 'impressions'
                ? 'bg-white text-[#2864EA] shadow-2xs'
                : 'text-[#64748B] hover:text-[#111827]'
            }`}
          >
            Estimated impressions
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('posts')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
              activeTab === 'posts'
                ? 'bg-white text-[#2864EA] shadow-2xs'
                : 'text-[#64748B] hover:text-[#111827]'
            }`}
          >
            Posts
          </button>
        </div>
      </div>

      {/* Leaderboard List */}
      <div className="divide-y divide-slate-100">
        {sorted.map((creator, index) => {
          const rank = index + 1;
          const currentVal = activeTab === 'impressions' ? creator.impressions : creator.posts;
          const pct = Math.min(100, Math.max(8, Math.round((currentVal / maxVal) * 100)));

          const displayValue =
            activeTab === 'impressions'
              ? `${Math.round(creator.impressions / 1000)}K`
              : `${creator.posts}`;

          const subText =
            activeTab === 'impressions'
              ? 'estimated Naano impressions'
              : 'posts published';

          return (
            <div
              key={creator.id || index}
              className="py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-slate-50/50 transition-colors px-2 rounded-xl"
            >
              {/* Left Column: Rank + Avatar + Name + Link */}
              <div className="flex items-center gap-3.5 min-w-0">
                {/* Rank Number / Badge */}
                <div className="w-7 flex items-center justify-center shrink-0">
                  {rank === 1 ? (
                    <span className="w-6 h-6 rounded-full bg-[#FEF3C7] text-[#D97706] font-bold text-xs flex items-center justify-center shadow-2xs">
                      1
                    </span>
                  ) : rank === 2 ? (
                    <span className="w-6 h-6 rounded-full bg-[#F1F5F9] text-[#64748B] font-bold text-xs flex items-center justify-center">
                      2
                    </span>
                  ) : rank === 3 ? (
                    <span className="w-6 h-6 rounded-full bg-[#FFEDD5] text-[#C2410C] font-bold text-xs flex items-center justify-center">
                      3
                    </span>
                  ) : (
                    <span className="text-xs font-semibold text-[#64748B]">
                      {rank}
                    </span>
                  )}
                </div>

                {/* Creator Avatar */}
                <div className="w-9 h-9 rounded-full overflow-hidden border border-slate-200 shrink-0 bg-slate-100 shadow-2xs">
                  <img
                    src={creator.avatarUrl}
                    alt={creator.name}
                    className="w-full h-full object-cover"
                  />
                </div>

                {/* Creator Name & Public card link */}
                <div className="min-w-0">
                  <h3 className="text-sm font-bold text-[#111827] truncate leading-snug">
                    {creator.name}
                  </h3>
                  <Link
                    href={creator.cardUrl}
                    className="text-[11px] text-[#94A3B8] hover:text-[#2864EA] transition-colors block mt-0.5 truncate"
                  >
                    {creator.subtitle || 'Public creator card'}
                  </Link>
                </div>
              </div>

              {/* Right Column: Progress Bar + Metric Number + Label */}
              <div className="flex items-center gap-4 sm:gap-6 shrink-0 self-end sm:self-center pl-10 sm:pl-0">
                {/* Visual Blue Bar on Gray Track */}
                <div className="w-32 sm:w-48 md:w-64 h-1.5 rounded-full bg-slate-100 overflow-hidden shrink-0">
                  <div
                    className="h-full rounded-full bg-[#2864EA] transition-all duration-500 ease-out"
                    style={{ width: `${pct}%` }}
                  />
                </div>

                {/* Stats Number and Sub-label */}
                <div className="text-right min-w-[110px] sm:min-w-[130px]">
                  <span className="text-sm font-extrabold text-[#111827] block leading-tight">
                    {displayValue}
                  </span>
                  <span className="text-[10px] text-[#94A3B8] block leading-tight font-normal mt-0.5">
                    {subText}
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
